### ISSUE TITLE
Unable to detect single digit numbers

### ISSUE THREAD

**Issue by adiamante** [henrivain/TesseractOcrMaui#18]
Hi,

The following jpeg images are not able to be read:

![1](https://github.com/henrivain/TesseractOcrMaui/assets/72841758/5e3bfc30-d118-4e9d-90ad-47b205a7daa3)
![2](https://github.com/henrivain/TesseractOcrMaui/assets/72841758/eb5616c2-4bcf-495f-b96a-4d05297c9408)
![3](https://github.com/henrivain/TesseractOcrMaui/assets/72841758/a57bbf76-6d7a-4ff2-8a8f-e738143ca176)

The following does work so I'm guessing it's unable to read single digits.

![524](https://github.com/henrivain/TesseractOcrMaui/assets/72841758/382eb54c-a9a8-4c75-8b14-cc68a9d356fc)

I tested in windows TesseractOcrMauiTestApp project along with an android app.   For android, I do know Xamarin.Tesseract package is able to read them properly but I am attempting to phase it out.

**Comment by henrivain** [comment]
Hi,
Check if setting DefaultSegmentationMode property in TessEngine helps. Are you trying to only detect single digit numbers or do you have numbers that might be single digit in some cases?


``` csharp
using TessEngine engine = new("eng", "path/to/tessdatadir");
engine.DefaultSegmentationMode = PageSegmentationMode.SingleChar;
```

See [PageSegmentationMode enum](https://github.com/henrivain/TesseractOcrMaui/blob/master/TesseractOcrMAUI/Enums/PageSegmentationMode.cs)


Does the problem appear also with png images?

**Comment by henrivain** [comment]
I can find couple questions about the same problem

https://stackoverflow.com/questions/9632044/tesseract-does-not-recognize-single-characters

https://stackoverflow.com/questions/27581164/is-there-a-way-to-use-tesseract-for-single-digit-numbers

**Comment by adiamante** [comment]
@henrivain 

PageSegmentationMode.SingleChar worked but PageSegmentationMode.SingleLine worked better for my use case.

Thanks
