### ISSUE TITLE
Configure encoding/decoding to get non-ASCII characters (e.g., Chinese/Japanese/Korean etc.)

### ISSUE THREAD

**Issue by SunshineSpring666** [henrivain/TesseractOcrMaui#38]
Hi Henri,
Thanks a lot for the great library.  

I put the [chi_sim.traineddata](https://github.com/tesseract-ocr/tessdata_fast/blob/main/chi_sim.traineddata) into project and configured it in CreateMauiApp accordingly, but the test output contains scrambled characters. 

It looks like an encoding/decoding issue. Are there any ways to make such configuration?

Thanks a lot.
Best Regards,
Joe

**Comment by henrivain** [comment]
Hello,

Yeah it sounds like encoding issue. I also had one on windows. The library gets its recognized text from native tesseract library method 
`TESS_API char *TessBaseAPIGetUTF8Text(TessBaseAPI *handle);` 
I think dllimport might convert string to different encoding. In windows I converted string to byte array and encoded it to UTF-8 with following code. 

`result` is string that is returned from recignizion

`Encoding` class is from `System.Text` namespace

```cs
        var bytes = new byte[result.Length];
        for (int i = 0; i < result.Length; i++)
        {
            bytes[i] = (byte)result[i];
        }
        if (bytes is null)
        {
            return string.Empty;
        }
        try
        {
            return Encoding.UTF8.GetString(bytes);
        }
        catch (Exception ex)
        {
            throw new InvalidBytesException("Cannot encode current byte array, because it contains invalid bytes.", ex);
        }
```

Let me know if this helps

**Comment by SunshineSpring666** [comment]
Hi Henri,
I added the encoding process which takes the Tesseract output string as a bytearray, and encode it by UTF8. However I didn't get the expected result, it's still scrambled characters at my side.

So I attached the demo project and test data here ([MaApp.zip](https://github.com/henrivain/TesseractOcrMaui/files/14318513/MaApp.zip)). Please help check if something is wrong.

Thanks for your reply.
Best Regards,
Joe



![OutputScreenshot](https://github.com/henrivain/TesseractOcrMaui/assets/42401603/c0ef96c9-b766-406f-9d4d-b1a1d9e35b1d)

**Comment by henrivain** [comment]
Is the image from app or dev terminal

**Comment by SunshineSpring666** [comment]
The image as input is here:
![InputImage](https://github.com/henrivain/TesseractOcrMaui/assets/42401603/363ca4f3-1521-4cde-9d84-d45d4dc985e2)

And the output string is as follows:
%    x     K H } N bO

Strange enough, the string which clipboard grabbed skipped all the question-mark-in-diamond, as shown in the image:
![encoded_output_str](https://github.com/henrivain/TesseractOcrMaui/assets/42401603/4002e121-99ec-4932-ba79-d10c94edf702)


Below is the string before the additional UTF8 encoding process, it's almost the same as the Encoded one without line break:
%    x  ¹  K H } N bO

![tesseract_output](https://github.com/henrivain/TesseractOcrMaui/assets/42401603/ef63b055-4354-41f3-96c9-a13c297e967a)

It seems like the reencoding doesn't map the output into right characters. Could you please reproduce the output at your side？
Thanks.

**Comment by henrivain** [comment]
I test tomorrow if I have time. Looks very likely to be encoding problem, it might still need to be in different encoding than utf 8

**Comment by henrivain** [comment]
Is the text chinese are which language? I might need this information later.

**Comment by SunshineSpring666** [comment]
Yes, both the page and trained data are in [Simplified Chinese](https://github.com/tesseract-ocr/tessdata_fast/blob/main/chi_sim.traineddata). 

Below are some Simplified Chinese characters for testing purposes. You may just snip an image:

《静夜思》
床前明月光，疑是地上霜。
举头望明月，低头思故乡。

Best Regards,
Joe

**Comment by henrivain** [comment]
Hi, 

I think I have figured out how to fix the problem.
![image](https://github.com/henrivain/TesseractOcrMaui/assets/89461562/98a230d6-fdc8-4022-8999-b776e680aefb)

Dll import with string return type seems to mess up the encoding process. It probably replaces characters that can't be encoded with defined CharSet correctly with some other character and so changing the byte values. 

TesseractApi.cs
```cs
// This is old call
[DllImport(DllName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "TessBaseAPIGetUTF8Text", CharSet = CharSet.Ansi)]
public static extern string GetUTF8Text(HandleRef handle);
```

Setting return type as char pointer and handling string marshalling later seems to fix the problem (image at the start of this comment). I think I'll be adding new method in native api calls and handling string conversion after the call as below

TesseractApi.cs
``` cs
// Probably new call will be this
[DllImport(DllName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "TessBaseAPIGetUTF8Text")]
public unsafe static extern char* GetUTF8Text_Unsafe(HandleRef handle);
```

TessPage.cs
``` cs
unsafe
{
     char* ptr = TesseractApi.GetUTF8Text_Unsafe(Engine.Handle);
     string? result = Marshal.PtrToStringUTF8(new IntPtr(ptr));
}
```

I have still to test things to see that everything works. Changes must be made at my library level so there is no quick easy fix that you can do yourself now, but I try to get the change out quickly.

Henri

**Comment by SunshineSpring666** [comment]
Hi Henry,

That's great! Thanks for all your effort.

Best Regards,
Joe

**Comment by SunshineSpring666** [comment]
👍Thanks, Henry! Hope to see the updated NuGet package soon.
